sudo: true
os: linux
dist: bionic
language: python
git:
    submodules: false
python:
  - "3.6"
  - "3.7"
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
addons:
  apt:
    update: true
    packages:
      - python3-gi
      - python3-sqlalchemy
      - gir1.2-snapd-1
      - zenity
      - gir1.2-packagekitglib-1.0
      - python3-distro
      - libgirepository1.0-dev
      - packagekit
      - snapd
      - dbus
      - dbus-x11
      - python3-coverage
      - python3-pytest
      - python3-venv
matrix:
  fast_finish: true
  include:
    - os: linux
      dist: bionic
install:
  - make setup_dev
script: sudo python3 -m pytest -v