sudo: required
os: linux
dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - sudo apt update
  - sudo apt install -y python3-gi python3-sqlalchemy gir1.2-snapd-1 zenity gir1.2-packagekitglib-1.0 python3-distro
matrix:
  include:
    - os: linux
      dist: bionic
script: make unittest