sudo: required
os: linux
dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
addons:
  apt:
    update: true
    packages:
      - python3-gi
      - python3-sqlalchemy
      - gir1.2-snapd-1
      - zenity
      - gir1.2-packagekitglib-1.0
      - python3-distro
      - libgirepository1.0-dev
      - packagekit
      - snapd
      - dbus
      - dbus-x11
matrix:
  include:
    - os: linux
      dist: bionic
script: make unittest